name: On Pull Request to Master branch

on:
  pull_request:
    branches:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Checkout the target branch
        uses: actions/checkout@v2
        with:
          ref: ${{github.base_ref}}

      - name: Pull all other branches
        run: git fetch
        shell: bash

      - name: Checkout the source branch
        run: git checkout --track origin/${{github.head_ref}}

      - name: Merge with the target branch
        run: git merge ${{github.base_ref}}
        shell: bash

      - name: Caching Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
              ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B clean verify -P !contract-test --file pom.xml

